import type { Metadata } from "next";
import React from "react";
import DashboardLayout from "../../../components/layout/DashboardLayout";
import getSession from "@/lib/getSession";
import { UserRole } from "@prisma/client";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Admin Approval",
  description: "Generated by create next app",
};

export default async function ArticleLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getSession();

  if (!currentUser || currentUser?.user?.role !== UserRole.ADMIN) {
    return redirect("/");
  }

  return <>{children}</>;
}
