import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Artikel",
  description: "Generated by create next app",
};

export default function ArticleLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
