import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/provider/QueryProvider";
import Navbar from "@/components/layout/Navbar";
import SideBar from "@/components/layout/SideBar";
import ModalProvider from "@/components/provider/ModalProvider";
import { Toaster } from "@/components/ui/toaster";
import Providers from "@/components/provider/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
          <ModalProvider />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
