import type { Metadata } from "next";
import React from "react";
import DashboardLayout from "../../components/layout/DashboardLayout";

export const metadata: Metadata = {
  title: "Buat Artikel",
  description: "Generated by create next app",
};

export default function ArticleLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <DashboardLayout>{children}</DashboardLayout>
    </>
  );
}
